config/routes.rb
Rails.application.routes.draw do
  resources :preparatories
  resources :answers

  #lessons/:id/steps/:id
  resources :lessons do
    resources :steps
  end

  #get 'users/index'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: {sessions: 'users/sessions'}
  resources :users do
    member do
      get :delete_image_attachment
    end
  end
  #get '/users/:id/edit_password', to: 'users#edit_password', as: 'user_cazzo'

  get 'pages/home'
  get 'mockups/page_a'
  get 'mockups/edu_sign_in'
  get 'mockups/edu_index'
  get 'mockups/edu_student_bookmark'
  get 'mockups/edu_faq'
  get 'mockups/sign_in'
  get 'mockups/homepage'
  get 'mockups/lessons_index'
  get 'mockups/lessons_show'
  get 'mockups/lessons_show_steps_show'
  get 'mockups/users_show'
  get 'mockups/users_edit'
  get 'mockups/users_index'
  get 'mockups/youtube_player'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #root 'pages#home'
  root 'lessons#index'
end

app/models/step.rb
class Step < ApplicationRecord
  # == Constants ============================================================
  
  # == Extensions ===========================================================

  ## i18n dynamic
  extend Mobility
  translates :question, type: :string
  translates :cheneso, type: :string
  translates :youtube_video_id, type: :string
  
  # == Attributes ===========================================================

  # == Relationships ========================================================

  ## many-to-one
  belongs_to :lesson

  ## one-to-many
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true, reject_if: proc{ |attr| attr['content'].blank? }

  # == Validations ==========================================================

  # == Scopes ===============================================================

  # == Callbacks ============================================================

  # == Class Methods ========================================================

  # == Instance Methods =====================================================
  def next
    lesson.steps.where("id > ?", id).first
  end

  def prev
    lesson.steps.where("id < ?", id).last
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_lesson
  before_action :set_step, only: %i[ show edit update destroy ]

  # GET /steps or /steps.json
  def index
    #@steps = Step.all
    @steps = @lesson.steps.order(id: "ASC")
    authorize @steps
  end

  # GET /steps/1 or /steps/1.json
  def show
    render layout: 'full_screen'
  end

  # GET /steps/new
  def new
    #@step = Step.new
    @step = @lesson.steps.new
    authorize @step
  end

  # GET /steps/1/edit
  def edit
  end

  # POST /steps or /steps.json
  def create
    #@step = Step.new(step_params)
    @step = @lesson.steps.new(step_params)
    authorize @step

    respond_to do |format|
      if @step.save
        #format.html { redirect_to step_url(@step), notice: "Step was successfully created." }
        format.html { redirect_to lesson_steps_path(@lesson), notice: 'Step was successfully created.' }
        format.json { render :show, status: :created, location: @step }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps/1 or /steps/1.json
  def update
    respond_to do |format|
      #raise "params[:step][:diary_chap] = #{params[:step][:diary_chap]} -- @step.diary_chap = #{@step.diary_chap}"
      #raise "current_user.role = #{current_user.role}"
      if @step.diary_chap > 0 or current_user.role == "admin" 
        #Aggiorna lo step e vai avanti
        if @step.update(step_params)
          #format.html { redirect_to step_url(@step), notice: "Step was successfully updated." }
          #format.html { redirect_to lesson_step_path(@lesson), notice: 'Step was successfully updated.' }
          format.html do 
            if @step.next.present?
              redirect_to lesson_step_path(@lesson, @step.next.id), notice: 'Step was successfully updated.' 
            else
              redirect_to lesson_step_path(@lesson), notice: 'Step was successfully updated. - Ultima risposta'
            end
          end
          format.json { render :show, status: :ok, location: @step }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @step.errors, status: :unprocessable_entity }
        end
      else
        #----
        #Non aggiornare lo step e vai solo avanti
        format.html do 
          if @step.next.present?
            redirect_to lesson_step_path(@lesson, @step.next.id), notice: 'Step was successfully updated.' 
          else
            redirect_to lesson_step_path(@lesson), notice: 'Step was successfully updated. - Ultima risposta'
          end
        end
        format.json { render :show, status: :ok, location: @step }
        #----
        #tutto questo blocco è stato aggiunto semplicemente per evitare di salvare la risposta sul db. *_*
      end
    end
  end

  # DELETE /steps/1 or /steps/1.json
  def destroy
    @step.destroy

    respond_to do |format|
      #format.html { redirect_to steps_url, notice: "Step was successfully destroyed." }
      format.html { redirect_to lesson_steps_path(@lesson), notice: 'Step was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:lesson_id])
    end

    def set_step
      #@step = Step.find(params[:id])
      @step = @lesson.steps.find(params[:id])
      authorize @step
    end

    # Only allow a list of trusted parameters through.
    def step_params
      params.require(:step).permit(:id, :question, :lesson_id, :youtube_video_id, :diary_chap, answers_attributes: [:_destroy, :id, :content, :user_id])
    end
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/steps/_answer_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= form.hidden_field :_destroy %>
    <%= form.hidden_field :user_id, required: true, class: 'form-control', value:current_user.id  %>
    <%= form.text_field :content, placeholder: "rispondi", autofocus: true, autocomplete: "off", class: "form-control" %>
  </div>
</div>

app/views/steps/_form.html.erb
<%#= form_with(model: step) do |form| %>
<%= form_with(model: [@lesson, step]) do |form| %>
  <% if step.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
        <% step.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :question, style: "display: block" %>
    <%= form.text_field :question %>
  </div>

  <div>
    <%= form.label :diary_chap, style: "display: block" %>
    <%= form.number_field :diary_chap %>
  </div>

  <div>
    <%= form.label :youtube_video_id, style: "display: block" %>
    <%= form.text_field :youtube_video_id %>
  </div>

  <!-- da eliminare -->
  <div>
    <%= form.label :lesson_id, style: "display: block" %>
    <%= form.text_field :lesson_id %>
  </div>

  <div>
    <%= form.label :id, style: "display: block" %>
    <%= form.text_field :id %>
  </div>
  <!-- da eliminare -->

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/steps/_step.html.erb
<div id="<%= dom_id step %>">
  <p>
    <strong>Lesson:</strong>
    <%#= step.lesson_id %>
    <%= step.lesson.name %>
  </p>

  <p>
    <strong>Step_id:</strong>
    <%= step.id %>
  </p>

  <p>
    <strong>Question:</strong>
    <%= step.question %>
  </p>

  <p>
    <strong>diary_chap:</strong>
    <%= step.diary_chap %>
  </p>

  <p>
    <strong>Answers of logged User</strong>
    <ul>
      <% step.answers.where(user_id: current_user.id).each do |answer| %>
        <li>
          <%= answer.content %> - by <%= answer.user.username %>
        </li>
      <% end %>
    </ul>
  </p>
</div>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render "form", step: @step %>

<br>

<div>
  <%#= link_to "Show this step", @step %>
  <%= link_to "Show this step", [@lesson, @step] %> |
  <%#= link_to "Back to steps", steps_path %>
  <%= link_to "Back to steps", lesson_steps_path(@lesson) %>
</div>

app/views/steps/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Steps</h1>

<div id="steps">
  <% @steps.each do |step| %>
    <%= render step %>
    <p>
      <%#= link_to "Show this step", step %>
      <%= link_to "Show this step", lesson_step_path(@lesson, step) %>
      <%= link_to 'Show this Lesson', [@lesson] %>
    </p>
    <hr/>
  <% end %>
</div>

<%#= link_to "New step", new_step_path %>
<%= link_to 'New Step', new_lesson_step_path(@lesson) %>

app/views/steps/new.html.erb
<h1>New step</h1>

<%= render "form", step: @step %>

<br>

<div>
  <%#= link_to "Back to steps", steps_path %>
  <%= link_to "Back to lesson steps", lesson_steps_path(@lesson) %>
</div>

app/views/steps/show.html.erb
<!-- Questo è il singolo step di una lezione. è il video con la domanda alla fine. -->
<!-- Questa pagina non è influenzata dal toggle light/dark-mode perché non è stato riportato nel layout full_screen. Lo lasciamo sempre scuro perché aiuta la concentrazione. -->
<!-- **************** MAIN CONTENT START **************** -->
<main>
<section class="py-0 bg-dark position-relative">

	<div class="row g-0">
		<div class="d-flex">
			<!--<div class="overflow-hidden fullscreen-video w-100">-->
        <!--<div style="width: 100%; min-width: 100px; max-width: 1200px;" class="d-block mx-auto">-->

          <!--<div id="player-papa" style="position: relative; width:100%; overflow:hidden; padding-top: 56.25%;">-->
          <div id="player-papa">
            <!-- 1. The <iframe> (and video player) will replace this <div> tag. -->
            <div id="player" style="position: absolute; top: 0; left: 0; right: 0; width: 100%; height: 100svh; border:none;"></div>
          </div>

					<!-- 1b. The <div> with <form> that replaces the video player <iframe> tag. -->
					<div id="<%= dom_id @step %>" style="display: block; margin-left: auto; margin-right: auto;">
						<%= form_with(model: [@lesson, @step], local: true, id: "answer-form", html: {'data-turbo': "false", style: "display: none; "}) do |form| %>
							<!-- =======================
							Newsletter START -->
							<section class="pt-5 pt-lg-0">
								<div class="container position-relative overflow-hidden pt-5">
									<!-- SVG decoration -->
									<figure class="position-absolute top-50 start-50 translate-middle ms-3">
										<svg>
											<path class="fill-white opacity-3" d="m496 22.999c0 10.493-8.506 18.999-18.999 18.999s-19-8.506-19-18.999 8.507-18.999 19-18.999 18.999 8.506 18.999 18.999z"/>
											<path class="fill-white opacity-3" d="m775 102.5c0 5.799-4.701 10.5-10.5 10.5-5.798 0-10.499-4.701-10.499-10.5 0-5.798 4.701-10.499 10.499-10.499 5.799 0 10.5 4.701 10.5 10.499z"/>
											<path class="fill-white opacity-3" d="m192 102c0 6.626-5.373 11.999-12 11.999s-11.999-5.373-11.999-11.999c0-6.628 5.372-12 11.999-12s12 5.372 12 12z"/>
											<path class="fill-white opacity-3" d="m20.499 10.25c0 5.66-4.589 10.249-10.25 10.249-5.66 0-10.249-4.589-10.249-10.249-0-5.661 4.589-10.25 10.249-10.25 5.661-0 10.25 4.589 10.25 10.25z"/>
										</svg>
									</figure>
									
									<div class="bg-grad p-3 p-sm-5 rounded-3">
										<div class="row justify-content-center position-relative">
											<!-- SVG decoration -->
											<figure class="fill-white opacity-1 position-absolute top-50 start-0 translate-middle-y">
												<svg width="141px" height="141px">
													<path d="M140.520,70.258 C140.520,109.064 109.062,140.519 70.258,140.519 C31.454,140.519 -0.004,109.064 -0.004,70.258 C-0.004,31.455 31.454,-0.003 70.258,-0.003 C109.062,-0.003 140.520,31.455 140.520,70.258 Z"/>
												</svg>
											</figure>
											<!-- Newsletter -->
											<div class="col-12 position-relative my-2 my-sm-3">
												<div class="row align-items-center">
													<!-- Title -->
													<div class="col-lg-12">
														<h3 class="text-white mb-3 mx-3"><%= @step.question %></h3>

														<% if current_user == "admin" %>
															<p>fanculo: <%= form.number_field :diary_chap %> cazzo</p>
														<% else %>
															<%= form.hidden_field :diary_chap %>
														<% end %>

														<!-- Creiamo nuovo Record -->
														<%= form.fields_for :answers, Answer.new do |answer| %>
															<%= render "answer_fields", form: answer %>
														<% end %>
														<div class="actions bg-dark-input">
															<%= form.submit class: "btn btn-lg btn-primary"%>
															<%#= form.submit "esegui", class: "btn btn-lg btn-primary" %>
														</div>
													</div>
												</div>
											</div>
										</div> <!-- Row END -->
									</div>
								</div>
							</section>
							<!-- =======================
							Newsletter END -->
						<% end %> <!-- answer-form END -->
					</div>

					<!-- 1c. If it's the final step than show this. -->
					<div id="last-step" style="display: none;">

							<!-- =======================
							Newsletter START -->
							<section class="pt-5 pt-lg-0">
								<div class="container position-relative overflow-hidden pt-5">
									<!-- SVG decoration -->
									<figure class="position-absolute top-50 start-50 translate-middle ms-3">
										<svg>
											<path class="fill-white opacity-3" d="m496 22.999c0 10.493-8.506 18.999-18.999 18.999s-19-8.506-19-18.999 8.507-18.999 19-18.999 18.999 8.506 18.999 18.999z"/>
											<path class="fill-white opacity-3" d="m775 102.5c0 5.799-4.701 10.5-10.5 10.5-5.798 0-10.499-4.701-10.499-10.5 0-5.798 4.701-10.499 10.499-10.499 5.799 0 10.5 4.701 10.5 10.499z"/>
											<path class="fill-white opacity-3" d="m192 102c0 6.626-5.373 11.999-12 11.999s-11.999-5.373-11.999-11.999c0-6.628 5.372-12 11.999-12s12 5.372 12 12z"/>
											<path class="fill-white opacity-3" d="m20.499 10.25c0 5.66-4.589 10.249-10.25 10.249-5.66 0-10.249-4.589-10.249-10.249-0-5.661 4.589-10.25 10.249-10.25 5.661-0 10.25 4.589 10.25 10.25z"/>
										</svg>
									</figure>
									
									<div class="bg-grad p-3 p-sm-5 rounded-3">
										<div class="row justify-content-center position-relative">
											<!-- SVG decoration -->
											<figure class="fill-white opacity-1 position-absolute top-50 start-0 translate-middle-y">
												<svg width="141px" height="141px">
													<path d="M140.520,70.258 C140.520,109.064 109.062,140.519 70.258,140.519 C31.454,140.519 -0.004,109.064 -0.004,70.258 C-0.004,31.455 31.454,-0.003 70.258,-0.003 C109.062,-0.003 140.520,31.455 140.520,70.258 Z"/>
												</svg>
											</figure>
											<!-- Newsletter -->
											<div class="col-12 position-relative my-2 my-sm-3">
												<div class="row align-items-center">
													<!-- Title -->
													<div class="col-lg-12">
														<h3 class="text-white mb-3 mx-3">CONGRATULATION</h3>
														<%= link_to 'Repeat Lesson', [@step.lesson], class: "btn btn-primary mb-0 mx-1" %>
														<%= link_to 'Next Lesson', lessons_path, class: "btn btn-primary mb-0 mx-1" %>

													</div>
												</div>
											</div>
										</div> <!-- Row END -->
									</div>
								</div>
							</section>
							<!-- =======================
							Newsletter END -->
					</div>

        <!--</div>-->

        <script>
          // 2. This code loads the IFrame Player API code asynchronously.
          var tag = document.createElement('script');

          tag.src = "https://www.youtube.com/iframe_api";
          var firstScriptTag = document.getElementsByTagName('script')[0];
          firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

          // 3. This function creates an <iframe> (and YouTube player)
          //    after the API code downloads.
          var player;
          function onYouTubeIframeAPIReady() {
            player = new YT.Player('player', {
              //height: '390',
              //width: '640',
              //videoId: 'M7lc1UVf-VE',
              videoId: '<%= @step.youtube_video_id %>',
              playerVars: {
								//'autoplay': 1, // 1 = autoplay, 0 = no autoplay
								'controls': 0, // 0 = controls do not display in the player, 1 = they display
								//'modestbranding': 1, // Hide the Youtube Logo
								'fs': 0, // Hide the full screen button
								//'showinfo': 0, // Hide related videos at the end
								'rel': 0, //related videos will come from my channel 
                'playsinline': 1 //0 = fullscreen on mobile, 1 = non fullscreen
              },
              events: {
                'onReady': onPlayerReady,
                'onStateChange': onPlayerStateChange
              }
            });
          }

          // 4. The API will call this function when the video player is ready.
          function onPlayerReady(event) {
            event.target.playVideo();
          }

          // 5. The API calls this function when the player's state changes.
          function onPlayerStateChange(event) {
            if (event.data == YT.PlayerState.PLAYING) {
              console.log("PLAYING");
            }
            if (event.data == YT.PlayerState.PAUSED) {          
              console.log("PAUSED");
							// mettiamo il video in fullscreen
							//let playerDiv = document.getElementById('player') // prendiamo il tag con id="player"
							//playerDiv.requestFullscreen()
            }
            if (event.data == YT.PlayerState.ENDED) {
              console.log("ENDED - Evviva ^_^");
							//document.exitFullscreen(); // togliamo lo schermo intero (perché se è stato messo freeza tutto se nascondiamo il player)
              let playerDiv = document.getElementById('player-papa'); // prendiamo il tag con id="player"
              playerDiv.style.display = "none"; //Nascondiamo il player
              //let playerDiv = document.getElementById('player') // prendiamo il tag con id="player"
              //playerDiv.style.display = "none" //Nascondiamo il player
							if (<%= @step.next.present? %>) { 
								let formTest = document.getElementById('answer-form'); // prendiamo il tag con id="answer-form"
								formTest.style.display = "block"; //Mostriamo il form
							} else {
								let lastStep = document.getElementById('last-step'); // prendiamo il tag con id="last-step"
								lastStep.style.display = "block"; //Mostriamo il div
							}
            }
          }
        </script>

				<!-- Plyr resources and browser polyfills are specified in the pen settings -->
			<!--</div>-->

		</div>
	</div>

	<div class="row g-0">
		<div class="col-lg-12 d-grid">
			<%= link_to 'Esci dalla Lezione', [@step.lesson], class: "btn btn-danger-soft mb-0 mx-1" %>
		</div>

		<% if current_user.admin? %>
			<h6>Sezione Admin</h6>
			<p>Diary-chap: <%= @step.diary_chap %></p>

        <!-- Pagination START -->
        <div class="col-12">
          <nav class="mt-4 d-flex justify-content-center" aria-label="navigation">

						<nav aria-label="pager"  class="pagy-bootstrap-nav" role="navigation">
							<ul class="pagination">
								<% if @step.prev.present? %>    
									<li class="page-item prev">
										<%= link_to "<Prev #{@step.prev.id}", lesson_step_path(@lesson, @step.prev.id), class: "page-link", 'data-turbo': false %>
									</li>
								<% else %>    
									<li class="page-item prev disabled">
										<a href="#" class="page-link"><%= '<prev' %></a>
									</li>
								<% end %>

								<li class="page-item disabled"><%= link_to @step.id, "#", class: "page-link" %></li>

								<% if @step.next.present? %>    
									<li class="page-item next">
										<%= link_to "#{@step.next.id} Next>", lesson_step_path(@lesson, @step.next.id), class:"page-link", 'data-turbo': false %>
									</li>
								<% else %>
									<li class="page-item next disabled">
										<a href="#" class="page-link"><%= 'next>' %></a>
									</li>
								<% end %>
						  </ul>
						</nav>

          </nav>
        </div>
        <!-- Pagination END -->

			<%#= @step.prev.id if @step.prev.present? %>
			<%#= link_to '<Prev', lesson_step_path(@lesson, @step.prev.id), 'data-turbo': false if @step.prev.present? %>
			<%#= @step.id %>
			<%#= link_to 'Next>', lesson_step_path(@lesson, @step.next.id), 'data-turbo': false if @step.next.present? %>
			<%#= @step.next.id if @step.next.present? %>
			<br/>
			<div class="d-flex align-items-center mt-2 mt-md-0">
				<%= link_to 'Edit this step', edit_lesson_step_path(@lesson, @step), class: "btn btn-warning mb-0 mx-1" %>
				<%= link_to 'Back to lesson steps', lesson_steps_path(@lesson), class: "btn btn-success mb-0 mx-1" %>
				<%= button_to "Destroy this step", [@lesson, @step], method: :delete, class: "btn btn-danger mb-0 mx-1" %>
			</div>

		<% end %>

	</div>
</section>
</main>
<!-- **************** MAIN CONTENT END **************** -->